# Generated by Django 4.0.5 on 2022-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_project_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.IntegerField(null=True),
        ),
    ]
