# Generated by Django 4.0.5 on 2022-12-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='leader_grade',
            field=models.IntegerField(default=0),
        ),
    ]
